#!/bin/bash -l
## Project code
#PBS -A UCIE0003
## Job name
#PBS -N round1_validation
## Queue
#PBS -q main
## Output log format
#PBS -j oe
## Email notifications
#PBS -m abe
## How long do I want on the nodes
#PBS -l walltime=8:00:00
## Computational allocation
#PBS -l select=1:ncpus=128:mpiprocs=128

### Set temp to scratch
export TMPDIR=${SCRATCH}/${USER}/temp && mkdir -p $TMPDIR

# Load modules to match compile-time environment
module --force purge
module load ncarenv/23.09 intel/2024.2.1 craype/2.7.31 ncarcompilers/1.0.0 gcc-toolchain/13.2.0 cray-mpich/8.1.29 geos/3.12.1 proj/9.2.1 conda/latest

# Activate conda environment
conda activate mgsim

# Set up MPI environment
export MPICH_SINGLE_HOST_ENABLED=0
export MPICH_DPB_DIR=/glade/derecho/scratch/$USER/dpm

# Run script
mpiexec -n 1 --job-aware --single-node-vni --network def_tles=0 --universe-size=128 Rscript -e 'library(knitr); knit("/glade/u/home/pilowskyj/mgsim/Scripts/round1_validation.qmd")'



