#!/bin/bash -l
## Project code
#PBS -A UCIE0003
## Job name
#PBS -N mgsim_round1.5
## Queue
#PBS -q main
## Output log format
#PBS -j oe
## Email notifications
#PBS -m abe
## How long do I want on the nodes
#PBS -l walltime=8:00:00
## Computational allocation
#PBS -l select=1:ncpus=128:mpiprocs=128

### Set temp to scratch
export TMPDIR=${SCRATCH}/${USER}/temp && mkdir -p $TMPDIR

# Load modules to match compile-time environment
module --force purge
module load ncarenv/23.06 intel/2023.0.0 ncarcompilers/1.0.0 netcdf/4.9.2 proj/8.2.1 openmpi/main conda/latest geos/3.9.1 hdf5/1.12.2

# Activate conda environment
conda activate mgsim

# Run script
Rscript /glade/u/home/pilowskyj/mgsim/Scripts/simulation_round1.R

